### ISSUE TITLE
Rerun on smallish sample

### ISSUE THREAD

**Issue by lizgzil** [nestauk/dap_prinz_green_jobs#106]
Rerun on first 5k of mixed sample to check all our extra changes didnt break anything

**Comment by lizgzil** [comment]
I did this. The results look fine to me, but I guess we don't have a strong metric to test this on. I know we spoke in the past about creating a gold standard test set of results.

2x2 plots of the data can be found in this folder: https://drive.google.com/drive/folders/1OpxzTSyyflFvFXXe6JYdqxvxA6T8JGx6
they look ok to me (i.e. looking at outliers and making sure they make sense).

## Top 10 SOCs mapped to 

Sustainability officers                                           219
Software developers                                                91
Business and financial project management professionals n.e.c.     84
Company secretaries and finance managers                           71
Marketing consultants                                              54
Marketing managers                                                 52
Bookkeepers, payroll managers and wage clerks n.e.c.               48
Production managers and directors in manufacturing                 47
Business sales executives                                          43
Collector salespersons and credit agents                           43

## Top 10 SICs mapped to
Financial service activities, except insurance and pension funding     386
Environmental consulting activities                                    206
Wholesale trade, except of motor vehicles and motorcycles              143
Manufacture of machinery and equipment nec                             133
Management of real estate on a fee or contract basis                   115
Land transport and transport via pipelines                             104
Retail trade, except of motor vehicles and motorcycles                 100
WATER SUPPLY; SEWERAGE, WASTE MANAGEMENT AND REMEDIATION ACTIVITIES     99
Manufacture of computer, electronic and optical products                92
Civil engineering                                                       83

## Top green skills mapped to 

environmental engineering                           470
health and safety regulations                       423
promote sustainability                              420
promote innovative infrastructure design            133
promote sustainable energy                          120
inform customers on environmental protection        103
energy efficiency                                   102
ensure compliance with environmental legislation     95
climate change impact                                84
develop environmental policy                         80

## Top all skills mapped to 
communication                  1338
demonstrate enthusiasm         1109
attend to detail                667
use microsoft office            635
troubleshoot                    506
use spreadsheets software       486
taking a proactive approach     444
work in an organised manner     435
project commissioning           364
negotiate with stakeholders     357


## The **most** green jobs - where all 3 measures are greater than the average

Most common job titles

Sustainability Manager              20
Sustainability Consultant           12
Senior Sustainability Consultant    10
Estate Manager                       7
Assistant Property Manager           6

Most common SIC

Environmental consulting activities                                    66
Management of real estate on a fee or contract basis                   34
Management consultancy activities (other than financial management)    25
Financial service activities, except insurance and pension funding     25
Wholesale trade, except of motor vehicles and motorcycles              23

Most common SOC

Sustainability officers                       101
Landlords, property, and housing managers      24
Building and building services engineers       16
Energy engineers                               16
Environmental professionals n.e.c.             15

## The **least** green jobs - where all 3 measures are less than the average

Most common job titles

Catchment Operator           6
ICA Technician               5
Delivery Driver              4
Field Service Engineer       3
Senior Operations Manager    3

Most common SIC

WATER SUPPLY; SEWERAGE, WASTE MANAGEMENT AND REMEDIATION ACTIVITIES        35
Crop and animal production, hunting and related service activities         17
Waste collection, treatment and disposal activities; materials recovery    15
Freight air transport and space transport                                  12
Manufacture of glass and glass products                                    12

Most common SOC

Software developers                                     6
Bookkeepers, payroll managers and wage clerks n.e.c.    6
Dry cleaners and laundry workers                        6
Delivery drivers and couriers n.e.c.                    5
Signal workers                                          5

**Comment by india-kerle** [comment]
close I guess as we're running on the big guy now
