### ISSUE TITLE
clean up green jobs explorer dataset

### ISSUE THREAD

**Issue by india-kerle** [nestauk/dap_prinz_green_jobs#119]
we need to:
1. make sure every occupation only has 5 locations associated to it;
2. filter for occupations with 50 job adverts

**Comment by lizgzil** [comment]
hmm
```
occ_agg_data = load_s3_data(
        BUCKET_NAME,
        f"outputs/data/ojo_application/extracted_green_measures/analysis/occupation_aggregated_data_20231215.csv",
)
r = occ_agg_data['top_5_itl2_prop'].apply(pg.safe_literal_eval)
sum(r.apply(lambda x: len(x[0]))>5)
```
gives 0

So I'm not sure how there were >5 locations

**Comment by india-kerle** [comment]
very odd... followed that slack thread though with suraj so seems alls sorted - can the issue be closed now?
