### ISSUE TITLE
Graph iterations

### ISSUE THREAD

**Issue by india-kerle** [nestauk/dap_prinz_green_jobs#121]
A combination of feedback from lauren orso + spotting issues along the way:

 - [x] **Violin viz**
- [x] make it a beeswarm plot instead such that the violin plot is actual dots and highlight the occupation in a different color dot 
- [ ] (if beeswarm) get rid of the scroll list to explore occupations  
- [x] make points more transparent so it's not a huge blob 
- [x] more whitespace between the plots

**2x2 viz: occupations**

- [x] reword indicators in lay terms i.e. mean occupational green timeshare -> average time spent on green tasks in occupation
- [ ] reword tooltips i.e. There are 96 job ads in waste collection. The average time spent on green skills is above average at 19%. The industry emits 22297 greenhouse gas emissions.
- [ ] label quadrant lines i.e. above average time spent of green tasks 
- [ ] label one or two industries in each area of the chart to help users interpret the relative position of the data points 
- [x] add zoom functionality 
- [x] Remove drop down from occupation 2x2 x-axis. also change colours to reverse (green highest)

**2x2 viz: industries**
- [x] subtitle to read: Select an industry measure and compare it against the average share of green skills within the occupation
- [x] remove 'Industry' for each industry measure 

**Regional viz**
- [x] improve subtitle for more clarity
- [x] have a top 3 and bottom 3 appear next to the map in a list for each measure
- [x] values in the regional plot don't match between the chloropleth and the bar?
- [x] regional drop down rename itl_1_code
- [x] set itl_2 to default
- [ ] change bar in regional plot to nested for most and least - see https://github.com/altair-viz/altair/issues/2198
- [ ] bar plot axis labels are getting cut off on left (ok to happen on the right)

**Top Skills viz**
- [x] add descriptions of the top green skills in tooltip

**skill similarity viz**
- [x] occupation similarity - colour by the prop green skills

**New Skills viz**
- [x] don't use TF-IDF as label
- [ ] turn it into a table with a mini bar chart in each row and show the rank i.e. the most visited art museums in the world 
- [ ] "Degree centrality" isn't clear
- [ ] anything to add to a hover over?

**Consistency across plots**
- [ ] Make sure there is consistency with how we phrase the measures e.g. "Average proportion of green skills"
- [ ] Convert proportion of green skills to % everywhere (often its 0.2 rather than 20%). We have fraction of time spent on green tasks in %, so it'd be nice if they were the same.
- [ ] round to the same decimal points everywhere
- [ ] y-axis labels to not be vertical?
- [ ] clean occupation everywhere! (n.e.c still popping up)
- [ ] bigger font sizes in labels
- [ ] selectors at the tops of the charts - needs to be added in html see https://stackoverflow.com/questions/62103632/altair-change-the-position-of-a-slider

## consistent names:
- Average percentage of green skills
- Percentage of green skills
- Average percentage of time spent on green tasks
- Percentage of time spent on green tasks
- Average GHG emissions per unit of economic output
- GHG emissions per unit of economic output

```
graph_config = pt.configure_plots(graph.configure(autosize="fit-x"), 
                                  chart_title='Most common skills',
                                  fontsize_normal=16,
                                    fontsize_title=18,
                                    )
```

**Comment by lizgzil** [comment]
On the Regional viz improvements

 - improve subtitle for more clarity
 - have a top 3 and bottom 3 appear next to the map in a list for each measure
 
I've made this which is stored [here](https://drive.google.com/file/d/13EJoQWb3OoIVGdNDdvxbfY3SKiRkgI6K/view?usp=drive_link):
<img src="https://github.com/nestauk/dap_prinz_green_jobs/assets/15956065/8f60c63a-e859-400c-942f-d244e3b592b1" width="400">

I had a go making the chloropleth with Flourish but came into some issues:
- Not being able to filter by 2 variables at once (i.e. ITL and green measure type), so I just did ITL3
- Not being to export to html without a pro license (I'm sure we could get one though)
- Not sure if it possible to put two plots next to each other like that and have them be controlled by the same filter?
- It's a bit sad how un reproducible the plots are? Lots of manual steps to wrangle the data

This is the flourish attempt:
<img src="https://github.com/nestauk/dap_prinz_green_jobs/assets/15956065/abed3f0c-834f-4a27-ae86-66b0b9ac2e9d" width="200">

I'll leave pushing any changes to regional_comparison.ipynb until we decide what to do about using Flourish or not!

**Comment by india-kerle** [comment]
FYI @lizgzil I've played around with data wrapper (the tool that suraj suggested) to try to make the 2x2 typologies graph and was able to create the following:

<img width="642" alt="Screenshot 2024-01-16 at 11 31 08" src="https://github.com/nestauk/dap_prinz_green_jobs/assets/46863334/905c6496-1b2c-447c-a637-c83ebfe7a5b7">

**Pros:**
- simple to add tooltips and create a responsive graph
- has a download data functionality already embedded in the graph
- no manual work - I just downloaded the industry aggregated dataset we've already created and could filter in the front end

**Cons:**
I couldn't make the graph 'responsive' or have drop down functionality. When I had a google, [it looks like they don't have that ability out of the box but they provide examples of work arounds (as long as you know html/javascript)](https://academy.datawrapper.de/article/305-how-to-add-tabs-and-drop-downs)

I'll have a google for any other similar tools that allow for drop down functionality but it looks like data wrapper could be easier than flourish (based on your experience)

**Comment by india-kerle** [comment]
okay [there seems to be many different types of tools like flourish. ](https://medium.com/spatial-vision/7-of-the-best-data-visualisation-platforms-146075f586b9 )

I took a look at [RAWgraph](https://app.rawgraphs.io/) also - i'm not totally sure if you can create a filter in the front end but it looks like again, they allow for customisability should you know some javascript. It looks like we have two options then:
1. ask suraj to add filter functionality to the graphs we want to create;
2. just move forward with altair and define our own width and height to use

Let's see what he says!
