### ISSUE TITLE
green skills analysis

### ISSUE THREAD

**Issue by india-kerle** [nestauk/dap_prinz_green_jobs#15]
based on extracted green skills baseline, explore:

- [x] summary statistics on green skills just flagged with skills sample;
- [x] summary statistics on baseline extracted green skills from raw ojo sample;
- [x] look into different thresholds on a smaller sample of job adverts

**Comment by india-kerle** [comment]
**based on 1st approach of flagging skills identified as green from whole esco taxonomy:**

Number of job adverts with at least one green skill:  1876
% of job adverts with at least one green skill:  ~1.87%
--------- count of job adverts with x green skills: ---------
0    98124
1     1646
2      189
3       27
4       10
5        4

most common green skills:

1. health and safety regulations (238)
2. develop management plans (111)
3. waste management (85)
4. develop environmental remediation strategies (66)
5. manage waste (65)
6. promote sustainability (58)
7. dispose waste (57)
8. environmental engineering (56)
9. asbestos removal regulations (54)
10. identify new recycling opportunities (40)
11. dispose medical waste (39)
12. follow health and safety procedures in construction (36)
13. corporate social responsibility (35)
14. ensure correct goods labelling (32)
15. promote innovative infrastructure design (28)
16. assess environmental impact (28)
17. test samples for pollutants (27)
18. ensure compliance with environmental legislation (25)
19. manage habitats (25)
20. report on environmental issues (25)

reed occs with the most green skills requested:

sector | green_skill_codes | count
-- | -- | --
Management Consultant | e4ff825c-7376-4135-93cd-3892fd67b7c1 | 60
Asbestos Surveyor | d13f1685-9848-4c9e-a40a-686ddb407858 | 24
Cleaner | 89f5fa96-ae45-4906-902c-d50ca51009c6 | 21
Other | f2f463e5-2382-49cb-8199-e7e043d868df | 19
Trades &amp; Labour | f2f463e5-2382-49cb-8199-e7e043d868df | 15
Warehouse Operative | f2f463e5-2382-49cb-8199-e7e043d868df | 12
Warehouse Operative | 6fcf2fc7-7b74-42e5-845f-f5854fd44f37 | 11
Other Manufacturing | f2f463e5-2382-49cb-8199-e7e043d868df | 10
Environmental | 9f763ac3-1d6c-48d2-ab54-324b1b144f40 | 9
Health &amp; Safety Manager/SHEQ Advisor | f2f463e5-2382-49cb-8199-e7e043d868df | 9

top raw job titles with green skills requested:

job_title | green_skill_codes | count
-- | -- | --
Agile Transformation Consultant | e4ff825c-7376-4135-93cd-3892fd67b7c1 | 60
Production Operative | f2f463e5-2382-49cb-8199-e7e043d868df | 8
Cleaner | 6f900dcb-c7ff-4d97-8015-9c45b99f7097 | 6
Cleaner 11 to 20 hours | 89f5fa96-ae45-4906-902c-d50ca51009c6 | 6
Domestic Assistant | 40fa39b5-0f69-432a-b5ea-b01b5d98649a | 6
Warehouse Operative | f2f463e5-2382-49cb-8199-e7e043d868df | 5
Retail Cleaner 3 hours | f2f463e5-2382-49cb-8199-e7e043d868df | 5
Asbestos Surveyor Analyst | d13f1685-9848-4c9e-a40a-686ddb407858 | 5
Grounds Operative Cemetery | eadf0f36-cba0-4e68-8458-c91bc60b494d | 4
Air Quality Associate/ Senior Associate - Birm... | 9f763ac3-1d6c-48d2-ab54-324b1b144f40 | 4

I've also labelled the top 50 matches for quality ("skill_match_thresh": 0.7).

**48.9%** of matches seemed **good**:

extracted_skill | matched_skill | count | match_quality [0 - bad, 1- ok, 2- good]
-- | -- | -- | --
Adhering to all health and safety rules and re... | health and safety regulations | 18 | 2.0
waste disposal | carry out appropriate waste disposal | 14 | 2.0
Asbestos Awareness | regulations covering asbestos removal | 13 | 2.0
adhering to Health and Safety regulations | health and safety regulations | 11 | 2.0
creating a culture of sustainability in which ... | encourage sustainability | 11 | 2.0
health and safety regulations | health and safety regulations | 10 | 2.0
waste management | waste management | 8 | 2.0
Waste | deal with waste | 7 | 2.0
knowledge of Health and Safety legislation | health and safety regulations | 7 | 2.0
Prepare management reports | prepare management plans | 7 | 2.0
Waste disposal | carry out appropriate waste disposal | 6 | 2.0
waste | deal with waste | 6 | 2.0
Knowledge of health and safety regulations | health and safety regulations | 6 | 2.0
Risk assessing the environment | assess environmental risks | 6 | 2.0
understanding of health and safety legislation | health and safety regulations | 5 | 2.0
Knowledge of Health and Safety Regulations | health and safety regulations | 5 | 2.0
decontamination | decontamination techniques | 4 | 2.0
Understanding all Asbestos Legislations | legislation covering asbestos removal | 4 | 2.0
health and safety rules | health and safety regulations | 4 | 2.0
Knowledge of Health and Safety legislation | health and safety regulations | 4 | 2.0
infrastructure design | foster innovative infrastructure design | 4 | 2.0
Adhering to strict health and safety guidelines | health and safety regulations | 4 | 2.0
heating systems | industrial heating systems | 4 | 2.0
adhering to Health and Safety legislation | health and safety regulations | 4 | 2.0

**44.9%** of matches seemed **ok**:

extracted_skill | matched_skill | count | match_quality [0 - bad, 1- ok, 2- good]
-- | -- | -- | --
understanding remediation plans | environmental remediation strategies developing | 30 | 1.0
prioritising remediation plans | developing environmental remediation strategies | 30 | 1.0
the waste and recycling sections | analyse new recycling opportunities | 24 | 1.0
water | consuming water | 16 | 1.0
minimise waste | managing waste | 10 | 1.0
River | river and stream protecting | 10 | 1.0
climate change projects | climate change impact | 10 | 1.0
ensuring that waste is disposed of safely | dispose of dangerous waste | 9 | 1.0
protecting | game protecting | 9 | 1.0
Monitor compliance | monitor compliance with noise standards | 8 | 1.0
monitor compliance | monitor compliance with noise standards | 7 | 1.0
reducing waste | managing waste | 7 | 1.0
conducting analysis | conducting sample analysis | 6 | 1.0
waste services | waste management | 6 | 1.0
maintaining our green spaces | content of green space strategies | 6 | 1.0
Asbestos awareness | regulations covering asbestos removal | 5 | 1.0
input of disposal information | waste disposal overseeing | 5 | 1.0
Conducting analysis | conducting sample analysis | 5 | 1.0
Producing and compiling air quality assessment... | managing air quality | 4 | 1.0
developing plans | management plans developing | 4 | 1.0
leading waste and resource management companies | waste managing | 4 | 1.0
laboratory waste | chemical waste | 4 | 1.0

**6.1%** of matches seemed **bad** due to bad extracted skill span:

extracted_skill | matched_skill | count | match_quality [0 - bad, 1- ok, 2- good]
-- | -- | -- | --
provide the best environment | manage natural environments | 5 | 0.0
Display energy | energy need identifying | 4 | 0.0
An environment | manage natural environments | 4 | 0.0

**Comment by india-kerle** [comment]
**based on 2nd approach of flagging skills identified as green from esco green taxonomy:**

Number of job adverts with at least one green skill: 7967
% of job adverts with at least one green skill: ~7.97%

--------- count of job adverts with x green skills: ---------
0    92033
1     6566
2     1100
3      208
4       69
5       18
6        4
7        2

the most common extracted green skills are:

[('health and safety regulations', 1193),
 ('ensure compliance with environmental regulations', 613),
 ('application of health and safety standards', 465),
 ('responsible business', 345),
 ('give advice on environmental risk management systems', 286),
 ('assess environmental risks', 286),
 ('perform cleaning activity in an environmentally friendly way', 285),
 ('safety engineering', 274),
 ('analysing biological data', 215),
 ('ensure environmental protection in work practices', 172),
 ('performing cleaning activities in an environmentally friendly way', 144),
 ('identify adequate packaging for food products', 119),
 ('coverage of health and safety standards', 111),
 ('maintaining recycling records', 107),
 ('ensure the safety of protected areas', 102),
 ('managing waste', 99),
 ('management plans developing', 90),
 ('perform environmentally friendly cleaning activities', 86),
 ('waste management', 80),
 ('chemical waste', 79)]

reed occs with the most green skills requested:

sector | count
-- | --
Qualified Social Worker | 7
Other Transport &amp; Logistics | 7
Other Strategy &amp; Consultancy | 6
Other Hospitality &amp; Catering | 6
Manufacturing | 6
Trades &amp; Labour | 6
Support Worker | 6
Registered Nurse Band 6 | 6
Administrator | 6
Driving | 5

top raw job titles with green skills requested:

job_title | count
-- | --
Warehouse Operative | 206
COVID-19 Vaccination Programme Clinical Supervisor | 126
Production Operative | 112
Cleaner | 60
HGV Class 1 Driver | 59
Duty Manager | 52
Live in carer | 50
Venue Based Charity Fundraising/Promotions | 49
Amazon Warehouse Operative | 37
Warehouse Associate | 37

I've also labelled the top 50 matches for quality ("skill_match_thresh": 0.7).

**4%** of matches seemed **good**:

extracted_skill | matched_skill | count | match_quality [0 - bad, 1- ok, 2- good]
-- | -- | -- | --
Adhering to safety, quality and production sta... | application of health and safety standards | 234 | 2
Site Management | site prospection management | 11 | 2

**14%** of matches seemed **ok**:

extracted_skill | matched_skill | count | match_quality [0 - bad, 1- ok, 2- good]
-- | -- | -- | --
risk management | give advice on environmental risk management s... | 49 | 1
cleaning materials | perform cleaning activity in an environmentall... | 15 | 1
Analyse data | analysing biological data | 13 | 1
cleaning | perform cleaning activity in an environmentall... | 13 | 1
picking or packing products | pick adequate packaging for food products | 12 | 1
Excel | analysing biological data | 10 | 1
analyse data | analysing biological data | 10 | 1

**82%** of matches seemed **bad**:

extracted_skill | matched_skill | count | match_quality [0 - bad, 1- ok, 2- good]
-- | -- | -- | --
assess and sign-off competence training of new... | chemical waste | 73 | 0
coordinate the vaccine preparation (drawing-up... | coordinate waste management procedures | 73 | 0
provide tailored support | perform cleaning activity in an environmentall... | 50 | 0
attention to detail | responsible business | 45 | 0
raising vital funds | use water disinfection equipment | 43 | 0
Strong communication skills | ensure environmental protection in work practices | 37 | 0
using computer systems | safety engineering | 37 | 0
managing contractors | health and safety regulations | 33 | 0
Self-motivated | biological data collecting | 29 | 0
Retail or similar background driven | health and safety regulations | 25 | 0
helping to support the nation | pick adequate packaging for food products | 24 | 0
pack food products | safety engineering work | 24 | 0
Staffline is proud | health and safety regulations | 24 | 0
enthusiastic | manage natural environments | 23 | 0
Starting and finishing | carry out appropriate waste disposal | 21 | 0
customer service | supervise waste disposal | 20 | 0
ensuring health | safety engineering | 19 | 0
enthusiastic | health and safety regulations | 19 | 0
learn new skills | health and safety regulations | 18 | 0
NaN | health and safety regulations | 17 | 0
work alongside and learn | manage natural environments | 16 | 0
deliver vehicles to customers ' specified requ... | engender enthusiasm for nature | 16 | 0
Loading, storing | health and safety regulations | 15 | 0
Excel | ensure compliance with environmental regulations | 15 | 0
Pallet truck deliveries | safety engineering | 15 | 0
showing new starters how to use the equipment | natural food supplies | 14 | 0
Excel | health and safety regulations | 14 | 0
Responsible | responsible business | 13 | 0
responsible | responsible business | 13 | 0
picking and packing products in our warehouse ... | perform cleaning activities with minimal damag... | 13 | 0
Strong report writing | carrying out environmental audits | 13 | 0
technical knowledge of mechanical and electric... | carrying out environmental audits | 12 | 0
engage with technical requests | efficiently manage warehouse space | 11 | 0
customer facing areas and employee areas are c... | analyse new recycling opportunities | 11 | 0
Operate industrial cleaning machinery | perform cleaning activity in an environmentall... | 11 | 0
the waste and recycling sections | perform cleaning activities in an environmenta... | 11 | 0
Kindness | perform cleaning activity in an environmentall... | 11 | 0
responding appropriately to queries and compla... | use adequate packaging for food products | 11 | 0
Delivering high maintenance standards across s... | responsible business | 11 | 0
build rapport with our customers to advise the... | perform cleaning activity in an environmentall... | 11 | 0
confidence in building rapport with a variety ... | medical threats from physical hazards | 10 | 0

**Comment by lizgzil** [comment]
great analysis!

**Comment by india-kerle** [comment]
Updated the second analysis to use interim outputs as the matches looked a bit buggy + did it on the new sample. 

Number of job adverts with at least one green skill: 8543
% of job adverts with at least one green skill: ~8.84%

--------- count of job adverts with x green skills: ---------
0     88078
1      7009
2      1161
3       270
4        71
5        20
6         5
7         4
8         1
9         1
10        1

the most common extracted green skills are:

[('social performance', 5116),
 ('responsible business', 3800),
 ('communicate with people about nature', 2303),
 ('commend customers on building materials', 1960),
 ('facilitate environmentally friendly work practices', 1718),
 ('health and safety regulations', 1703),
 ('management plan developing', 1470),
 ('promote responsible consumer behaviour', 1409),
 ('reporting on issues in the environment', 1385),
 ('management plans developing', 1327),
 ('waste oversight', 1261),
 ('develop management plans', 1249),
 ('inspiring enthusiasm for nature', 1244),
 ('prepare management plans', 1161),
 ('analysing biological data', 1147),
 ('inform customer environmental protection', 1026),
 ('ensure compliance with environmental regulations', 979),
 ('carry out field studies', 964),
 ('gamekeeping', 940),
 ('inspire enthusiasm for nature', 921)]

reed occs with the most green skills requested:

sector | count
-- | --
Other Strategy &amp; Consultancy | 85
Site Management | 80
Graduate Training Schemes | 77
Cleaner | 76
Administrator | 71
Other IT &amp; Telecoms | 70
Quality Control | 65
Other Transport &amp; Logistics | 60
Facilities Management | 57
Semi-skilled Operator | 57

top raw job titles with green skills requested:

job_title | count
-- | --
Warehouse Operative | 1279
Cleaner | 819
Project Manager | 545
Production Operative | 454
Operations Manager | 404
Site Manager | 400
Agile Transformation Consultant | 360
Administrator | 351
Senior Project Manager | 331
Store Manager | 283

I've also labelled the top 50 matches for quality ("skill_match_thresh": 0.7).

**14%** seemed **good**:

extracted_skill | matched_skill | count | match_quality [0 - bad, 1- ok, 2- good]
-- | -- | -- | --
Adhering to safety, quality and production sta... | application of health and safety standards | 104 | 2
Strong health and safety measures | health and safety regulations | 55 | 2
Health and safety | health and safety regulations | 54 | 2
health and safety | health and safety regulations | 30 | 2
Follow Health and Safety Guidelines | health and safety regulations | 18 | 2
knowledge of health and safety | health and safety regulations | 17 | 2
ensuring that waste is disposed of safely | dispose of dangerous waste | 17 | 2

and **86%** seemed **ok**:

extracted_skill | matched_skill | count | match_quality [0 - bad, 1- ok, 2- good]
-- | -- | -- | --
responsible | responsible business | 343 | 1
cleaning | perform cleaning activity in an environmentall... | 302 | 1
risk management | give advice on environmental risk management s... | 196 | 1
Ensuring compliance | ensure compliance with environmental regulations | 145 | 1
analysing data | analysing biological data | 115 | 1
Enterprise | social enterprise | 111 | 1
ensuring compliance | ensure compliance with environmental regulations | 83 | 1
risk assessment | assess environmental risks | 69 | 1
Ensure compliance | ensure compliance with environmental regulations | 66 | 1
maintaining records | maintaining recycling records | 66 | 1
analyse data | analysing biological data | 62 | 1
Maintaining records | maintaining recycling records | 52 | 1
Risk Management | give advice on environmental risk management s... | 51 | 1
Analysing data | analysing biological data | 40 | 1
packaging | identify adequate packaging for food products | 40 | 1
Maintain the outside cleanliness | perform cleaning activities in an environmenta... | 38 | 1
the waste and recycling sections | analyse new recycling opportunities | 38 | 1
ensure compliance | ensure compliance with environmental regulations | 35 | 1
cleaning duties | performing cleaning activities in an environme... | 35 | 1
cleaning experience | performing cleaning activities in an environme... | 31 | 1
ensuring safety | safety engineering | 27 | 1
Ensuring safety | safety engineering | 27 | 1
cleaning tasks | perform cleaning activity in an environmentall... | 27 | 1
cleaning activities | performing cleaning activities in an environme... | 25 | 1
Responsible | responsible business | 23 | 1
ensure the safety | ensure the safety of protected areas | 23 | 1
cleaning chemicals | disposing of chemicals correctly | 23 | 1
collecting data | biological data collecting | 22 | 1
assessing risk | assess environmental risks | 21 | 1
maintain compliance | ensure compliance with environmental regulations | 21 | 1
Identify risks | assess environmental risks | 21 | 1
Ensure safety | safety engineering | 21 | 1
Cleaning experience | performing cleaning activities in an environme... | 21 | 1
water | consuming water | 21 | 1
Complying with all Health and Safety policies ... | coverage of health and safety standards | 21 | 1
Follow regulations | ensure compliance with environmental regulations | 20 | 1
minimise waste | managing waste | 19 | 1
Risk management | give advice on environmental risk management s... | 18 | 1
Analyse data | analysing biological data | 18 | 1
improve efficiency | energy efficiency | 18 | 1
cleaning materials | perform cleaning activity in an environmentall... | 18 | 1
identify risks | assess environmental risks | 17 | 1
conducting audits | conducting energy audit | 17 | 1

**Comment by india-kerle** [comment]
Here are the # and % of job adverts with at least 1 skill based on different skill thresholds:

| skill threshold | # of jobs w/ at least 1 green skill | % of jobs with at least 1 green skill |
-- | -- | -- 
| 0.6 | 29326 | 30.36 |
| 0.7 | 8543 | 8.84 |
| 0.8 | 1486 | 1.54 |
| 0.9 | 209 | 0.22 |
