### ISSUE TITLE
Add more occupation green measures

### ISSUE THREAD

**Issue by lizgzil** [nestauk/dap_prinz_green_jobs#23]
Currently we just match to ONET green occupations, but there is also:
- ONET green tasks https://www.onetcenter.org/initiatives.html#green
- ONS green timeshare data  https://www.ons.gov.uk/economy/environmentalaccounts/datasets/estimatedtimespentongreentasksbyoccupationcode
- Green SOC https://www.skillsdevelopmentscotland.co.uk/media/49951/soc-categories-for-website.pdf

**Comment by india-kerle** [comment]
closing this as we've finalised the occupation datasets we are going to link with
