### ISSUE TITLE
Improve extracted skills 

### ISSUE THREAD

**Issue by india-kerle** [nestauk/dap_prinz_green_jobs#27]
we're currently using the full skills extractor pipeline to extract skills.

We could experiment by:
1. Improving existing infrastructure (i.e. fine tune a transformer model with job adverts and use it instead)
2. experiment with the mapping step of the pipeline i.e. cluster extracted skill spans

- We should also experiment with the level of 'greenness' of a skill i.e. some % of green
- Do we want to do anything with performing green tasks instead of green skills? i.e. train an NER model to predict tasks instead of skills?

**Comment by lizgzil** [comment]
we have retrained the NER model with more data. See this PR https://github.com/nestauk/ojd_daps_skills/pull/193

**Comment by india-kerle** [comment]
The green skills classifier branch has been merged - closing this
