### ISSUE TITLE
Finalising/adding to occupation greenness datasets

### ISSUE THREAD

**Issue by india-kerle** [nestauk/dap_prinz_green_jobs#38]

**Comment by india-kerle** [comment]
blocked by this [Asana ticket ](https://app.asana.com/0/1203688002767828/1204600882454742)

**Comment by lizgzil** [comment]
I reached out to Warwick to ask for the data behind this pdf of their greensoc https://www.skillsdevelopmentscotland.co.uk/media/49951/soc-categories-for-website.pdf

**Comment by lizgzil** [comment]
I also reached out to GLA to see if they are going to update their work based off the newer ONET work

**Comment by lizgzil** [comment]
We have a meeting with ONET where we can ask how best to incorporate their new green topics work

**Comment by lizgzil** [comment]
- Green SOC: blocked by getting permission + a csv of the data [ waiting for permission from Warwick]
- ONET Green topics: cant see how to download [the data](https://www.onetonline.org/search/green_topics/) [can ask O*NET when we chat with them, or ask the GLA guy whether they plan to do anything with this]

**Comment by lizgzil** [comment]
ONET have added the green topics download to the website now
