### ISSUE TITLE
B corp data for industries

### ISSUE THREAD

**Issue by lizgzil** [nestauk/dap_prinz_green_jobs#54]
There is potentially some good data at the [company level from Bcorp in the environmental category](https://www.bcorporation.net/en-us/find-a-b-corp/company/steenbergs-limited/).

![Screenshot 2023-07-10 at 10 00 53](https://github.com/nestauk/dap_prinz_green_jobs/assets/15956065/9cbdc8da-0ab2-4155-bc83-e3eff12dd616)

I don't think we can use it, but there is some [old data on data world](https://data.world/blab/b-corp-impact-data) (I think you need to pay for an account though)

From an email with bcorp:
> Unfortunately I'm unable to share any data with you that is not publicly available via[ the directory ](https://www.bcorporation.net/en-us/find-a-b-corp/)or the data world entries already. A representative of B Lab is updating the latter on a quarterly basis, so if this is not up-to-date now, I would just recommend waiting until the page gets updated.

**Comment by india-kerle** [comment]
Closing given we've finalised the external datasets we're using to link out to
