### ISSUE TITLE
Rerun measures on mixed sample

### ISSUE THREAD

**Issue by lizgzil** [nestauk/dap_prinz_green_jobs#75]
To get the 3 measures for the mixed sample of job adverts, we run 
```
python dap_prinz_green_jobs/pipeline/ojo_application/extract_green_measures.py --config_name "base" --production
``` 
Since each of the 3 measures are independently calculated, we can comment out parts of this script to just calculate one measure at a time. This has been handy when developing each of them separately, but at some point we need to make sure it's been run using each of the latest algorithms, so I'm opening this issue to make sure we do this.

- [x] Skills
Last run: 20230914
Output file: s3://prinz-green-jobs/outputs/data/ojo_application/extracted_green_measures/20230914/ojo_sample_skills_green_measures_production_True_base.json
Changes since last run?: No
Time taken: about 4 hours

- [x] Occupations
Last run: 20231002
Output file: s3://prinz-green-jobs/outputs/data/ojo_application/extracted_green_measures/20231002/ojo_sample_occupation_green_measures_production_True_base.json
Changes since last run?: No
Time taken: 5 mins

- [x] Industries
Last run: 20231013
Output file: s3://prinz-green-jobs/outputs/data/ojo_application/extracted_green_measures/20231013/ojo_sample_industry_green_measures_production_True_base.json
Changes since last run?: No
Time taken: ~1 day (running on EC2 instance)

**Comment by india-kerle** [comment]
Rerun on the mixed sample for all three metrics - closing
