### ISSUE TITLE
Included emissions per employee data for Industry?

### ISSUE THREAD

**Issue by lizgzil** [nestauk/dap_prinz_green_jobs#76]
Not sure how useful this is/what it adds, but we could include this data as a new industry measure:

https://www.ons.gov.uk/economy/environmentalaccounts/datasets/emissionsperemployeeuk2015to2021
![Screenshot 2023-09-27 at 09 48 35](https://github.com/nestauk/dap_prinz_green_jobs/assets/15956065/b6e4a438-4942-4d80-992a-728957f32bf9)

**Comment by india-kerle** [comment]
This was added in a previous, merged branch - closing
