### ISSUE TITLE
Update to use new SOCs

### ISSUE THREAD

**Issue by lizgzil** [nestauk/dap_prinz_green_jobs#82]
New SOC info has come out https://www.ons.gov.uk/methodology/classificationsandstandards/standardoccupationalclassificationsoc/standardoccupationalclassificationsocextensionproject

The "SOC2020 Volume2 the coding index (excel)_12-010-23 (4.5 MB xlsx)" download will need to replace our current indexsocextv5updated.xlsx one.

The columns arent all the same so it will be a bit more involved than just changing the input data.

Could be a good opporutnity to add the SOC name to the output of socmapper too.

**Comment by lizgzil** [comment]
I had just been thinking about this, so writing down some notes:
```
# Make dictionaries of SOC 2020 6 and 4 digit ids to names
self.soc_2020_6_2_name = dict(zip(jobtitle_soc_data['SOC 2020 Ext Code'], jobtitle_soc_data['SUB-UNIT GROUP DESCRIPTIONS']))
self.soc_2020_4_2_name = dict(zip(jobtitle_soc_data['SOC 2020'], jobtitle_soc_data['SOC 2020 UNIT GROUP DESCRIPTIONS']))
```

**Comment by india-kerle** [comment]
given our discussion yesterday from sprint planning, this is something we've chosen not to address in this project. Closing as a result
